name: CI
on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: jump-zrq
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          date
          uname -a
