name: demo-devops
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: pull 
        uses: actions/checkout@v3
     
      - name: mvn package
        run: |
          mvn clean package

      - name: docker build
        run: cd ./target && docker build -f ../dockerfile 
      
