name: Run Azure Login with OpenID Connect
on: [push]

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name:  test zrq env
      run:  echo ${{ secrets.ZRQ }} > 1.txt && cat 1.txt
