name: Run Azure Login with OpenID Connect
on: [push]

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
 
    - name: testzrq
     # run: echo ${{ secrets.AZURE_CLIENT_ID }} && echo ${{ secrets.AZURE_TENANT_ID }}&&echo ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run : az version     

    - name: az login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
