name: demo-devops
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v3
      - name: ls -a 
        run: |
          ls && echo "zrq" > ./1.txt && cat ./1.txt

