name: demo-devops
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: pull 
        uses: actions/checkout@v3
     
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: docker build
        run: docker build -t runoob/ubuntu:v1 . 
  
      - name: test
        run: ls &&docker images
